version: '3'

# Run as
#start mysql and python app containers
#docker-compose up 

#Rebuild python_app image 
#docker-compose up --build -d python_app

# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:
    mysql_db:
        image: mysql:5.7
        environment:   # Set up mysql database name and password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: weather_report
            MYSQL_USER: comatch
            MYSQL_PASSWORD: comatch
        networks:
            - app-tier
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./init.sql:/usr/src/app/init.sql
        ports:
            - 5555:3306
            - 5551:33060
    python_app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mysql_db
        networks:
            - app-tier
        command:
            tail -f /dev/null

networks:
  app-tier:
    driver: bridge